from typing import Any, Optional

class Deque:
    def addfirst(item: Any): ...
    def addlast(item: Any): ...
    def removefirst(item: Any) -> Optional[Any]: ...
    def removelast(item: Any) -> Optional[Any]: ...
    def len() -> int: ...
